name: Workshop Bruidsfotografie
favicon: null
layout_spectrum: 0.74085
typography_spectrum: 0.2215
title: Workshop Bruidsfotografie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9d7da'
    - '#e7c2b1'
    - '#f6ddda'
    - '#8dafbc'
    - '#c4a9b3'
  brandStrength: 0.5505570496898144
  lightness: 0.49644244252704084
  saturation: 0.40873049129731953
  rhythmicContrast: 0.7141380037646741
purpose: []
